### ISSUE TITLE
typing_extensions dependency Python < 3.8 selector

### ISSUE THREAD

**Issue by teake** [conda-forge/importlib_metadata-feedstock#57]
The upstream package has a Python < 3.8 selector on the `typing_extensions` dependency, which is not yet present in the feedstock. Should this be added or not? 

I've made a tentative PR to add it (#56), but closed it since it requires a rewrite from `noarch`. (I didn't fancy spending the time testing a non-`noarch` version of this package).

Edit: link to upstream dependency with selector: https://github.com/python/importlib_metadata/blob/v3.3.0/setup.cfg#L22.

**Comment by ocefpaf** [comment]
I believe that https://github.com/conda-forge/importlib_metadata-feedstock/pull/55 took care of this, no?

**Comment by teake** [comment]
No, I don't think so. It added the `typing_extensions` dependency but it omitted the "Python < 3.8" selector.

**Comment by ocefpaf** [comment]
That is a trick to keep it noarch. As far as I know `typing_extensions` on >=3.8 is just a stub, so no harm in having it installed.
